site_name: 'Enola AI Documentation'
site_description: 'Documentation for the Enola AI Python modules.'

# Specify the output directory for the built site
site_dir: docs

# Specify the source directory for the Markdown files
docs_dir: source_docs

nav:
  - Home: index.md
  - API Reference:
      - Enola Types: reference/enola_types.md
      - Evaluation: reference/evaluation.md
      - Get Executions: reference/get_executions.md
      - Tracking: reference/tracking.md
      - Tracking Batch: reference/tracking_batch.md

theme:
  name: 'material'
  features:
    - navigation.expand
  navigation:
    depth: 3

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ['src']
          setup_commands:
            - "import sys; sys.path.append('src')"
          docstring_style: google  # Specify the docstring style
