site_name: 'Enola AI Documentation'
site_description: 'Documentation for the Enola AI Python modules.'

nav:
  - Home: index.md
  - API Reference:
      - Enola Types: reference/enola_types.md
      - Evaluation: reference/evaluation.md
      - Get Executions: reference/get_executions.md
      - Step: reference/step.md
      - Tracking: reference/tracking.md
      - Tracking Batch: reference/tracking_batch.md

theme:
  name: 'material'  # If you didn't install mkdocs-material, you can use 'readthedocs'

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ['src']
          setup_commands:
            - "import sys; sys.path.append('C:/enola-1.3.5/src')"
